runtime: php
env: flex

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "8.3"

skip_files:
- ^.*\.bak$

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10

handlers:
- url: /public
  static_dir: public
- url: /.*
  script: auto

env_variables:
  APP_KEY: 'base64:5amyDyVZ5O0LT/Zz9iUu9oh3m2bJVGUsGGWm+vdslrQ='
  APP_ENV: 'local'
  APP_DEBUG: 'true'
  DB_CONNECTION: 'mysql'
  DB_HOST: '34.34.218.65'
  DB_DATABASE: 'finance_db'
  DB_USERNAME: 'root'
  DB_PASSWORD: '(|6"_},Dg)NLXq~j'
