runtime: php
env: flex

runtime_config:
  document_root: public


  skip_files:
  .env

  env_variable:
    APP_LOG: errorlog
    APP_KEY: base64:5amyDyVZ5O0LT/Zz9iUu9oh3m2bJVGUsGGWm+vdslrQ=
    STORAGE_DIR: /tmp
